### ISSUE TITLE
as a administrator I need to be able to update species data occasionally

### ISSUE THREAD

**Issue by lpendem** [nciinc/fs-permit-platform#104]
## Notes
maintain the species data in github as a json file so administrator can update when needed using source control.

## Acceptance Criteria
- [ ] administrator can add update delete species using source control

## Tasks
- [ ] move the data to json out of seeders

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This story should be tied to #14 Epic also

**Comment by ASprinkle** [comment]
closing because we have Story 316 for FS admin requesting changes.
