### ISSUE TITLE
As a user, I would like simple and clear language so that I may easily understand navigation and page content.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#134]
## Notes
This was identified in several usability tests:
[https://github.com/nciinc/fs-intake-module/wiki/Usability-testing-session-1-summary-November-6,-2017](https://github.com/nciinc/fs-intake-module/wiki/Usability-testing-session-1-summary-November-6,-2017)
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results)

## Acceptance Criteria
- [ ] all updates made as described and tested

## Tasks
- [ ] Remove the word "harvest" from the menu item labels and content.
- [ ] Work on plain language to better define the meaning of ‘district’ to users.
- [ ] Clarify language on "plantations" and "stands of trees" [(sprint 04 usability testing summary)](https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results)
- [ ] Replace "daylight hours" with operational hours.  [(sprint 04 usability testing summary)](https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results)

- [ ] Ensure consistent punctuation throughout the site (ie. am should be a.m.)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by JaneZC** [comment]
@ASprinkle @sadlerw    Hi Amber! I think this story can be archived/closed, as what we're working on now is likely taking care of this.

**Comment by ASprinkle** [comment]
Got it!
