### ISSUE TITLE
As a user, I would like a uniform presentation of the maps on the Find a forest page. 

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#197]
## Notes
This was an issue that based from the following usability tests:
[Sprint 05 UT Summary](https://github.com/nciinc/fs-intake-module/wiki/Sprint-05---Christmas-tree-ePermit-research-results---December-12,-2017)

[Sprint 06 UT Summary](https://github.com/nciinc/fs-permit-platform/wiki/Sprint-06-Christmas-tree-ePermit-research-results-January-3,-2018)

## Acceptance Criteria
- [ ] Minimize color palette of maps (possibly desaturate or make consistent between all maps)
- [ ] Make maps similar sizes
- [ ] Make labels hyperlinks

## Tasks
-[ ] Add 's' to the end of Arapaho-Roosevelt forest

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This will require work on behalf of each pilot forest to build new maps using the same symbol style. It is likely that this would have to be done via a Data Resources Management contract. I am not certain at this point that this is something we will have time to adequately address.

**Comment by JaneZC** [comment]
@ASprinkle I think for this one we were thinking much simpler; more along the lines of making sure the maps were of similar sizes and something that perhaps makes the colors a bit more 'matching.' 

Nothing fancier than that. Although your idea sounds much preferable, to be honest. :) (@bryanmcfadden )

**Comment by ASprinkle** [comment]
Thanks @JaneZC  I am curious how the maps could be resized to be the same without editing the content of the map in some way (scale especially, if there is one).  For the time being I will leave these here until I can think on this some more.

**Comment by ASprinkle** [comment]
Depending on what we do with #537, this story #197 may not be necessary.

**Comment by ASprinkle** [comment]
The work on #373 has eliminated the need for this story.
