### ISSUE TITLE
As a special forest products manager, I can retrieve the number of permits issued at any time, when they were issued and when they expire so that I can report out and reconcile.

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#20]
##Notes
- login and securing the endpoint should be a separate story
- ability to download as csv is a separate story

##Acceptance Criteria
- [ ] user can select report range and generate report
- [ ] report is formatted clearly and usably for onscreen viewing 

##Tasks

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
In this story a Forest Service employee would be able to access the website and run a report on x-mas tree e-permit sales.  The employee would ideally enter a query range (dates for example, Nov 1 2012- Nov 25 2012) and then the report would generate a list with the following columns: Name (last name), Permit Number, Issue Date. This report would be printable.

**Comment by hannahkane** [comment]
@ASprinkle - the title of this issue suggests that the expiration date is also important info. Should that be included in the report?

**Comment by ASprinkle** [comment]
Expiration dates are typically part of this kind of report that FS administrators are accustom to generating. Since this is a pilot for Christmas tree permits, it is assumed that the permit expires at the end of the season it is issued. If that is too much of a heavy lift, I can restructure the story to remove it.

**Comment by ASprinkle** [comment]
The combination of 283 and 285 resolves this story.  Retrieve # of permits issued at any time, when permits were issued and when they expire.  I recommend closing this story - thoughts?

**Comment by sadlerw** [comment]
ok with me!
