### ISSUE TITLE
As a user I want to trust that the information I am reading is accurate and up to date for each forest, so that I can feel good about conducting this business online.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#205]
## Acceptance Criteria
- [ ] All SMEs have validated the content for their forests as accurate

## Tasks
- [ ] update forest content in markdown, json, db based on SME content review findings

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This story will need to be broken out into 4 stories ( 1 for each forest ) - where each forest's page is reviewed for content accuracy, consistency against other forests' flow of information, and general functionality.

**Comment by ASprinkle** [comment]
Sprint 10 is covering this story with stories #428, #480 #479 #478
