### ISSUE TITLE
Skip to main content link is broken, does not move focus to content on activation

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#235]
## Notes
href="#skip-nav-target" is missing from the DOM.  Generally SkipNav would should just skip navigation and go to the main section.  I see main with an id of main-content, perhaps it just needs to be changed.

![image](https://user-images.githubusercontent.com/28604890/34465334-c4c3f502-ee75-11e7-8868-83e93269ef4f.png)

Linkage CTF-6, CTF-7
## Acceptance Criteria
- [x] WCAG 2.4 Navigable - 2.4.1 Bypass Blocks -  Skip Nav needs to have a valid href target on the current page.

## Tasks
- [x] fix html by adding id="skip-nav-target" tabindex="-1" (will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested
