### ISSUE TITLE
Permit Information pages have components that are not keyboard operable 

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#236]
## Notes
JAWS
Inconsistent behavior when pressing the Tab and Shift + Tab keys to move through page components.
 
Steps To Verify With JAWS:
 
Log on to the application. 
Activate the "Shoshone Map" link to move to the following URL: https://forest-service-trees-staging.app.cloud.gov/christmas-trees/forests/shoshone/tree-guidelines
Press the Tab key to move through page components.
When reaching the "forest or district map" link, press the Down Arrow to read any additional information about the link.
Press Shift + Tab to return to the "forest or district map" link. JAWS announces 'Main Region'. Focus has moved to the main content of the page. User must press Tab many times to return to the "forest or district map" link.
 
Issue using the Chrome and Firefox browsers but not when using Internet Explorer.
 
All functionality of the content must be operable through a keyboard interface.

Linkage: CTF-9

## Acceptance Criteria
- [x] WCAG 2.1 Keyboard Accessible - 2.1.1 Keyboard 

## Tasks
- [x] on tree guidelines check that tab order is correct for all sections, esp cutting areas and maps and fix (seth)
- [x] check tab order on form, confirmation and forest finder as well for consistent tab order (cameron)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by sethalt** [comment]
I couldn't reproduce the issue. I spoke with @JohnHewittCriterion and he was going to try and reproduce to issue to confirm that it is still valid.
