### ISSUE TITLE
Find a forest input is missing label linkage

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#237]
## Notes
The visible input label is not connected with for/id attributes. 

<label>Find a Forest:</label>
....
<input auto-complete="" display-property-name="description" id="forest-finder-input" min-chars="1" name="selectForest" placeholder="Type a forest name, city, or state..." value-property-name="id" class="ng-pristine ng-valid ng-touched">

![image](https://user-images.githubusercontent.com/28604890/34465461-dc74444e-ee7b-11e7-9f48-77da4f8dd9c1.png)

Linkage: CTF-10

## Acceptance Criteria
- [x] WCAG 1.3 Adaptable - 1.3.1 Info and Relationship 
Make sure the label wraps the input, contains "for" attribute or input contains 

## Tasks
- [x] add label (will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested
