### ISSUE TITLE
Find a forest search auto complete suggestion widget is not speaking the options with screen reader

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#238]
## Notes
When the user types a search value and suggestions appear the screen reader does not speak any announcement of the new suggestions. 

When the screen reader user hits the down arrow key they don't hear the selected options spoken. 

As you down arrow the same value in the input box is being read. (the letter f in the example image)
 
![image](https://user-images.githubusercontent.com/28604890/34465569-7d0b235c-ee7f-11e7-9cc3-dd8bc776dd0d.png)

Linkage: CTF-11

## Acceptance Criteria
- [x] WCAG - 1.3 Adaptable - 1.3.2 Meaningful Sequence 
Makes sure the list of items is announced properly
1) Make sure the fact that a list has appeared is announced
2) Make sure the individual items are announced when keyed through.

## Tasks
- [x] investigate aria tag needed to get dropdown to be read and then add to html (will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by sadlerw** [comment]
Since the typeahead/autocomplete isn't 508 compliant moving back to a select with options.  Does this look ok @tram ?

![Screen Shot 2018-01-17 at 5.08.43 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/64ae5126-39bf-42bd-be05-5c5f4a92cdbf)

**Comment by tram** [comment]
👍 "Find a forest that sells online Christmas trees" feels wordy, but it seems it's important enough to drive home—even regardless of accessibility issues.
🤔 Since it's reiterated in the subhead, could the label lose "pilot" and just be "Choose a forest"? My concern is that folks may find "pilot" confusing.

…or…

🤔 Another possibly cleaner option (pls double-check my accessibility work here) would be removing the "Find a forest…" subhead and changing the label to "Choose a forest that sells online Christmas tree permits". (The accessibility affordance here being that the natural reading order presented to a visitor using a screen reader ensures they would get the label if bailing out of the introductory paragraph thus passing SC 1.3.2.)

**Comment by sadlerw** [comment]
@tram So? ![Screen Shot 2018-01-18 at 7.51.44 AM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/e0db2542-e70e-47f9-90cd-e220366d4ec4)

**Comment by bryanmcfadden** [comment]
QQ..how do users find a forest near their city now? 
Using the previous typeahead design, they could at least type the city closest to them. 

I would think this just further validates the need for viewing forests by state which is in [story #256](https://github.com/nciinc/fs-permit-platform/issues/256).

**Comment by sadlerw** [comment]
The city nearest the forest is still in the dropdown.  You just have to read them all rather than type since it is a select.

**Comment by tram** [comment]
👍 New label LGTM.
