### ISSUE TITLE
Tree name bold title text is missing heading level 3 semantics

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#239]
## Notes
Make each strong tree name element a Heading at one level below its parent heading.

Visually it looks like these are headings, for those with asisstive the

![image](https://user-images.githubusercontent.com/28604890/34466290-04af8804-ee9c-11e7-8af8-3e2db36af9fd.png)

Linkage CTF-13

## Acceptance Criteria
- [x] WCAG - 1.3 Adaptable - 1.3.1 Info and Relationship 
Make sure the headings are used were the information is structured in discrete sets.

## Tasks
- [x] change span with strong to h3 (will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
![Screen Shot 2018-01-10 at 2.54.14 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/17c83971-f3f8-489b-9b53-6afbbcb56682)
