### ISSUE TITLE
On the Find a Forest page, headings are not structured hierachically

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#240]
## Notes
The Find a Forest page has four level 5 headings, but not other headings process them. Every HTML page should have one <h1> heading that captures the main title of the page, then headings should proceed that in hierarchical order.

https://forest-service-trees-staging.app.cloud.gov/christmas-trees/forests 

Linkage: CTF-15

## Acceptance Criteria
- [x] WCAG - 1.3 Adaptable - 1.3.1 Info and Relationship 

## Tasks
- [x] design html for adding headings (will)
- [x] edit html to add h1-h5 where needed (will)
- [x] design pre-approval from tts

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
@tram to get headings in this we need to add some headings...  does this work?

![Screen Shot 2018-01-10 at 10.15.36 AM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/e99ae50d-3e36-4bc4-b325-3164120da616)

**Comment by tram** [comment]
Love this issue and attention to accessibility!

The "Find a forest by city, state or name" subhead can be removed (leaving everything else as-is) and still pass WCAG SC 1.3.1 since the search applies to the main header and pilots to the subhead.

**Comment by sadlerw** [comment]
OK - also changed the wording on the h1 slightly since it starts with a verb  @JaneZC 
![Screen Shot 2018-01-10 at 2.58.01 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/5b0b18e7-834c-458e-abbf-c32cb8d9e97f)

**Comment by tram** [comment]
👍 LGTM! Ship it.

**Comment by sadlerw** [comment]
https://shipitsquirrel.github.io/

**Comment by JaneZC** [comment]
@sadlerw I think its fine for now. We'll work on the wording some more when we get to Story #257
