### ISSUE TITLE
On all pages, breadcrumb navigation is not identified properly

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#241]
## Notes
Each page on the site has breadcrumb navigation which is meant to orient users to where they are on the site and allow users an easy way back to previous pages in the navigation flow, but the breadcrumbs are not identified properly to assistive technology.
Breadcrumbs should be implemented as a <nav> element and have an accessible label as well as define the current page using ARIA, as in the example below.

<nav aria-label="Breadcrumb" class="breadcrumb">
<ol>
<li><a href="../../">WAI-ARIA Authoring Practices 1.1</a></li>
<li><a href="../../#aria_ex">Design Patterns</a></li>
<li><a href="../../#breadcrumb">Breadcrumb Pattern</a></li>
<li><a href="./index.html" aria-current="page">Breadcrumb Example</a></li>
</ol>
</nav>

Linkage: CTF-16

## Acceptance Criteria
- [x] WCAG - 1.3 Adaptable - 1.3.1 Info and Relationship 

## Tasks
- [x] add correct html to breadcrumbs (will)
- [x] use a component (will)
- [x] make short titles and title match - long title only in h1 (will)
- [x] fix class="breadcrumbs" (will)
- [ ] fix title service bug (Will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
@JohnHewittCriterion  hey do you care if the breadcrumb separator is a / instead of > ?  I think / makes more sense here

e.g.

![Screen Shot 2018-01-10 at 4.18.20 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/1388525d-36d9-4e49-8d32-7394d7bc52bb)

I'm using the css/wcag approach from https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html

**Comment by JohnHewittCriterion** [comment]
Slashes are fine, they are also in common usage.

**Comment by JohnHewittCriterion** [comment]
Is it possible to add aria-label="Breadcrumb" to the nav.  This will make it easier for screen reading users to identify this specific nav section more easily.
