### ISSUE TITLE
Epic - FS Administrator ability to generate reports for financial reporting or LEO use.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#246]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
