### ISSUE TITLE
As a user I would like to make sure the maps I am viewing are up to date and printable.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#248]
## Acceptance Criteria
- [ ] fs admin should be able to add or edit or delete a map for a new cutting area or district
- [ ] easy to use interface with upload capabilities
- [ ] preview functionality
- [ ] admin page secured to forest administrator only

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This epic would also include the FS administrator's ability to remove maps and upload new ones to their Forest's page.

**Comment by ASprinkle** [comment]
redundant with the connect stories. Not expected to take more than 1 sprint to accomplish.
