### ISSUE TITLE
As an FS Administrator I need to be able to update general information for my forest's Christmas tree page.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#249]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
