### ISSUE TITLE
As a user of the permit web site I need a site map so that I can easily find all permit types on the site

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#264]
## Notes
- we would place a link to the site map on the error page
- this is general site navigation and might not have to be part of the xmas tree effort

## Acceptance Criteria
- [ ] Sitemap page listing all pages and applications on the website
- [ ] links to the sitemap from footer and error page

## Tasks
- [ ] Create sitemap component
- [ ] Create link to sitemap from footer and error pages

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This is outside the scope of MVP for a user to obtain a Christmas tree permit online.
