### ISSUE TITLE
As a forest administrator or a LEO or a forest service employee I need to be able to login and generate reports for my forest only based on my permissions

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#280]
## Acceptance Criteria
- [ ] user can see and generate reports and links for their forest but not others based on permissions

## Tasks
- [ ] create simple fsadmin/reports page (just a link to the report page itself)
- [ ] secure link to report page using the permissions
- [ ] secure report page itself using same permissions
- [ ] if reports are saved for later retrieval make sure they are secured by same permission
- [ ] if eauth does NOT have forest and special products specific roles design system where whitelisted email addresses/users can be assigned to a forest and christmas trees by a permit site superuser (could be done in vcap)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Issue is no longer applicable, as LEO or FS Admin would access via eauth.
