### ISSUE TITLE
As a FS Admin I would like to request changes for my forest's christmas tree pages

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#316]
## Notes
- what happens after the change request is submitted is out of scope
- form will most likely go to a single central location/content editor
- form needs to designate forest
- fs admin needs to provide contact info

## Acceptance Criteria
- [ ] fs admins should be able to get to and use a form for requesting changes
- [ ] fs admins should be able to understand a process for sending in change requests

## Tasks
- [ ] create the google form content (Jane)
- [ ] set up form handling after submission (response email)
- [ ] design a publication/announcement process to the pilot forest admins 
- [ ] usability tested

**Comment by ASprinkle** [comment]
Changes would likely be requested for: 
Updating the season cutting dates and times, 
Removing or adding a species to the list of species.
Removing or adding cutting area maps (this includes the Shoshone, if they happen to have an area).
Updating specific cutting area dates and times
The "Rules" bullets under "How to cut your tree" which tie in with the "Rules to know" section. which would also update the Rules on the Buy a Christmas tree permit page.
Components of the "Contact us" section may need to be updated depending on the forest.

**Comment by JaneZC** [comment]
Hello everyone!

Here is a link to the Google Form - https://docs.google.com/forms/d/e/1FAIpQLSeBC23LA0KK0VTeKvqBtdRaxWfujvV_B_nzYRmvUsYYWW2VZw/viewform

Right now, this is built on my personal gmail account, and I wouldn't recommend keeping it that way for obvious reasons. If there is an account you'd prefer to be used, please let me know. I also wasn't sure to whom all these requests would be going to? 

I've also attached a very ugly PDF version of the form, in case that's easier to review.

[https://app.zenhub.com/files/106473503/c6b48baa-1f48-473c-af91-4d5e9a311b10/download](https://app.zenhub.com/files/106473503/c6b48baa-1f48-473c-af91-4d5e9a311b10/download)

There's not a lot of flexibility in the design of the form - we may want to request Nate to build us a picture that works with the background, for example - but I figure this will get us started.

**Comment by ASprinkle** [comment]
I spent some time reviewing the google form this afternoon. This is a great first step! Thank you for working on this. I do have a few comments for edits/changes.  Happy to discuss if you have questions.

-Page 1, I was unable to test the change your forest season cutting dates link due to an error that I receive (related to my eAuth login) that the team is working out right now.  So I would like to test that out later.
It would be good to only be able to select 1 forest here instead of multiple.

-Page 2,  delete this option/page. People can deal with asking for changes on another national forest via the "other" option on page 3

-Page 3, If page 2 is kept: I selected "No" on page 2  -that I don't need permissions to change another NF page, and then I didn't select a NF below.  When I selected"Next" to the 3rd page, I was not confident that the change I was requesting was going to be for the original NF I selected. Can the header reflect the name of the NF selected?  Or if we remove page 2 then the issue is solved. Can we change the question on page 3 to "What change(s) are you requesting?" add a sentence that says "select all that apply" In the green banner, can we change that to "Request Changes" and drop the "website content" piece? 

Here are my suggested edits to the selection list on page 3:
 	The cutting season date(s) need to be updated and I am unable to access the form to make those changes: https://forest-service-trees-staging.app.cloud.gov/admin/christmas-trees/season-dates.

	Permit price and/or the number of trees someone can buy

	Christmas tree cutting rules (i.e., diameter limits, height limits, and prohibited species)

	Changes to the printable permit

	Uploading or removing a map 

	Minor edits (i.e., grammar, style, word choice, spelling)

	New information to add to the site

	Other 

Is the "describe the change you want to see" limited to a certain number of characters?
If someone wants to upload a map, can they attach it to the form?
I am curious, what was the thought behind the choice/selection panel? What do  you think about only having the "Describe the change(s) you'd like to see" box (especially if it's not character limited)

-Page 4, the grayed out text where someone is supposed to populate the field "Your Answer" should be change to "Type Name Here" for "Name" and same for the other two fields. Can we remove the "Title" section, and change the "Email address" section to read "Your Forest Service Email Address".
I would like to know what happens before I hit the submit button.
 
-Page 5, "someone will be with you shortly" - Do we have a better statement that is confirmed for this? How about "We've received your request. You can expect a response to your request via the email address you provided within the next two business days."  
Have we figured out who the site custodian would be? or how this next step would occur? (an Aaron question probably).

**Comment by JaneZC** [comment]
Let me respond to this one first. :)

I am curious, what was the thought behind the choice/selection panel? What do  you think about only having the "Describe the change(s) you'd like to see" box (especially if it's not character limited)

By presenting both options, I'm hoping we can discuss what would work best for the form; its sometimes easier to delete things (than it is to recreate).

In a few meetings, I've heard folks essentially say "we don't know what kind of changes administrators will be requesting" and that this form will help determine that. In thinking about this, I thought it might be helpful to group requested changes into categories to make data collection about such content changes easier. (You can see an example graphic that Google provides below.) 

With that said ... I am more than okay with just have the "describe your change" box as it would probably be easier on administrators (one less question!) 

Happy to discuss.

![Screen Shot 2018-02-14 at 1.15.50 PM.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/5c17338b-feaa-40e1-ad84-3a22921ebebb)

**Comment by ASprinkle** [comment]
@JaneZC Ok, let's keep with the selection options vs. just the description box for now and see how that works. Thanks for the reminder on background.

**Comment by JaneZC** [comment]
Good morning!

I've made as many changes as possible; here we go:

Page 1: I've changed it so you can only select one forest.

Page 2: Deleted.

Page 3: I've updated the text in the selection to match what you have.

It does not appear that there is a character limit on the input box. 

I've added the "select all that apply' text. 

Dropped the 'website' text.

I added in the option to upload files. The bad news: it appears that you have to have a Google account to use this feature.

Page 4:

The bad news ... I do not think I can change the grey, unhelpful 'hint' text. (I agree with you, though, that it should be changed.)

I've changed the fields.

Page 5: I've updated the text.

Google Forms isn't very customizable 'out-of-the-box;' and some of the routing on this will be incorrect until it finds a true home.  

@MelissaBraxton Did you have any feedback?

Thanks!!

Jane                       

Link to Form: https://docs.google.com/forms/d/e/1FAIpQLSeBC23LA0KK0VTeKvqBtdRaxWfujvV_B_nzYRmvUsYYWW2VZw/viewform?c=0&w=1 

PDF Version of the Form
[https://app.zenhub.com/files/106473503/9a95f6be-aa77-426f-95ef-1a3ca97577f0/download](https://app.zenhub.com/files/106473503/9a95f6be-aa77-426f-95ef-1a3ca97577f0/download)

Email You Receive When Form Link is Sent To You
![Screen Shot 2018-02-16 at 7.41.12 AM.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/2121de66-f43d-4eac-bf67-bc43da8ef2ac)

**Comment by JaneZC** [comment]
@MelissaBraxton  @ASprinkle  Just an additional note - I know I mentioned a few times above, but there is not a lot of flexibility with this form and much of it is tied to folks being able to use Google (at least from what I know). At a certain point, it may just be easier to build out a (simple) form in the Christmas tree module.

**Comment by ASprinkle** [comment]
The requirement to have a google account to do something is a hard line. Maybe just remove the ability to upload stuff - and depend on the description box and the communication between the custodian and the user to get that information across.
I think this google form is a good starting place so long as people arent required to have a google account to fill it out. FS folks (from what I recall) aren't allowed to use Drive or Google stuff. Either that or we just don't for some reason.

Is this on page 1 because of the upload files feature?: "The name and photo associated with your Google account will be recorded when you upload files and submit this form. Not gsaambersprinkle@gmail.com? Switch account"

And can we remove this link on the last page after you submit "See previous responses"

Looking forward to our chat this morning!

**Comment by JaneZC** [comment]
@ASprinkle  @hannahkane   Thanks for meeting today! 

I've updated the form and think I've caught all the changes we talked about. Here is the link - https://docs.google.com/forms/d/e/1FAIpQLSeBC23LA0KK0VTeKvqBtdRaxWfujvV_B_nzYRmvUsYYWW2VZw/viewform?c=0&w=1 . A PDF version is attached below.

Also, I've added @hannahkane  as a "collaborator" so we should be able to transfer form ownership fairly easily. 

As a note, we discussed that next steps are outside the scope of this story. For example, figuring out the process for how content will be updated (who will get the emails, the owner of the account that will host the form, guidelines/deadlines for how long it'll take to respond to content change requests, etc.)          

@sadlerw  Can we add this as a link to the Change Season Dates page so we can test it out?  

[https://app.zenhub.com/files/106473503/a9eae789-002d-4279-ab47-83e6b39efee5/download](https://app.zenhub.com/files/106473503/a9eae789-002d-4279-ab47-83e6b39efee5/download)

**Comment by ASprinkle** [comment]
Thanks @JaneZC  it looks good. Consider it PO approved.

**Comment by MelissaBraxton** [comment]
We want to establish a consistent style and tone across the site, and I'd recommend discouraging people from asking for style and word choice changes. 

I think we should replace this:

	Minor edits (i.e., grammar, style, word choice, spelling)

With this:

	Minor corrections (i.e., inaccuracy, grammar, spelling)
