### ISSUE TITLE
As a user, I would like to see all the rules related to permits in the Rules to Know section on the order page.

### ISSUE THREAD

**Issue by JaneZC** [nciinc/fs-permit-platform#321]
## Notes
The goal is to consolidate the permit rules in one section and to ensure the user to check off that they've read it. (Right now, the user will not see permit rules in their entirety until they reach the permit.) 

Also, usability testing has shown that users are disoriented by the rules being placed in many places across the site and leads to questions about which ones are the most important.

## Acceptance Criteria
- [ ] all permit related rules (usage etc.) are in the permit rules section

## Tasks
- [ ] find all rules
- [ ] add them to the view
- [ ] consolidate into the same data table

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Is the suggestion to remove the "Rules" sub headers and respective bullets that are currently present under the "How to cut your tree" section?  Then only having the rules under the "Rules to know" section? And then again on the Buy a Christmas tree permit page?

**Comment by ASprinkle** [comment]
This story and #344 are separate stories with separate goals.  Let's reopen this story.

**Comment by sadlerw** [comment]
depends on research spike with SME

**Comment by ASprinkle** [comment]
Based on the discussions from the Sprint 9 Review regarding the flow of information on the site and recommendation (3) in story #428  I wonder if this story should be restructured - or I wonder if it is still relevant as is.

**Comment by bryanmcfadden** [comment]
@ASprinkle @JaneZC  - I agree with Amber....I don't think this story is relevant anymore due to story #428.

**Comment by JaneZC** [comment]
@ASprinkle @bryanmcfadden Agreed. The issues related to rules came up a while ago in usability testing; and this was put in at that time. We've since continued to refine the testing and subsequent results as it relates to the rules and its result is  #428.

**Comment by ASprinkle** [comment]
closing based on SME results and development of other stories that would address the issue.
