### ISSUE TITLE
As a user I want to make sure I understand what the Rules are that are printed on the permit, so that I don't confuse "rules" and "guidelines"

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#344]
## Notes
The goal is to consolidate the permit rules in one section and to ensure the user to check off that they've read it. (Right now, the user will not see permit rules in their entirety until they reach the permit.) 

Also, usability testing has shown that users are disoriented by the rules being placed in many places across the site and leads to questions about which ones are the most important.

## Acceptance Criteria
- [ ] user can see consistent presentation of the rules and guidelines on permit, website and email
- [ ] user can understand penalties incurred for not following the rules versus not following a guideline

## Tasks

- [x] **LEO card sorting exercise** (bryan, jane)
- [x]  - - develop card sorting exercise in OptimalSort (bryan, jane)
- [x]  - - draft LEO research protocol (bryan, jane)
- [x]  - - send card-sorting email requests to LEOs (48hr response) (bryan)

- [ ] **Change permit language on .svg** (bryan)
- [x]  - - draft design changes on permit .svg (bryan)
- [ ]  - - permit design changes approval
- [ ]  - - implementation of permit changes into website (will)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The rules box on the permit says "Guidelines". This title should be consistent with what we call Rules on the rest of the website, or we should re-name it so that it accurately reflects the importance of the information that follows.

**Comment by JaneZC** [comment]
I'd like to suggest that this be added to or considered with Story 321. I added 321 so we can take a bigger look at the rules and how they are grouped/categorized on the site. I think it would make sense to also re-evaluate what is on the site in the context of what is also on the permit.

**Comment by ASprinkle** [comment]
@JaneZC This story and story#321 are two separate issues with two separate goals.
This story renames the header of the bullet list of items on the permit to something more appropriate.  Rules if broken, may mean the user is in violation of their permit and could be fined. While guidelines could be stretched or not adhered to and the user may or may not be in violation of their permit.  The only "guideline" in the box on the permit that I see would be the leave no trace bullet.  We may want to focus this box to be more "permit instructions" and remove bullets associated with the Rules Agreed to, since the user already knows and agreed  to them.
Story #321 addresses the issue that having the rules are spread throughout the webpage is confusing to users, so they should be consolidated, and consistently represented on webpage, buy permit page, and permit.  I will reopen 321.

**Comment by bryanmcfadden** [comment]
Working with Jane and using initial data for rules and guidelines... I created 3 different designs for the rules on the permit.

**Design 1**
![sp_08_permit_design_updated_v 5 0 1](https://user-images.githubusercontent.com/16689692/35739165-bad304f0-07fe-11e8-9f07-875617bec5ef.jpg)


**Design 2**
![sp_08_permit_design_updated_v 5 0 2](https://user-images.githubusercontent.com/16689692/35739173-c1003c26-07fe-11e8-8ee8-d004632dbb9d.jpg)

**Design 3**
![sp_08_permit_design_updated_v 5 0 3](https://user-images.githubusercontent.com/16689692/35739177-c640112a-07fe-11e8-85e5-cf8443c6aa16.jpg)

Please note - Jane and I are still working on the page layout designs and are continuing to gather more data on the rules via card-sorting.

**Comment by ASprinkle** [comment]
I favor Design #2.  
A suggestion for edit in all design options is to combine the two bullets: 
The "Fill out using bold black ink" & the "on the date you cut your tree" instructions could possibly be combined into:
"On the date you cut your tree, fill in the month and day using bold black ink only (e.g., sharpie, marker, felt tip pen)".
Also, for the "I have read, understood, and agreed to the rules" language - can we specify "...rules for cutting a Christmas tree" so that it is known as different from the information to validate your permit?

**Comment by bryanmcfadden** [comment]
@ASprinkle - Something more like this?

![image](https://user-images.githubusercontent.com/16689692/35748769-24e3aafc-081d-11e8-99ac-b2f61d02589f.png)

**Comment by ASprinkle** [comment]
Yes, that looks great to me,  (add a period at the end of the first bullet statement.)

**Comment by bryanmcfadden** [comment]
@ASprinkle - Apparently when I was reading your comment I missed the first line..which indicated you liked design # 2 ..the previous edit was for design # 3. Here is the updated version for design # 2.  Would you still like to use design # 2 or the previous comment (design # 3)? 

![image](https://user-images.githubusercontent.com/16689692/35756009-94b0d912-0837-11e8-9c16-7647e67419a8.png)

**Comment by bryanmcfadden** [comment]
Updated .svg (Arial/Arial-Bold fonts corrected)
[permit-design.zip](https://github.com/nciinc/fs-permit-platform/files/1695683/permit-design.zip)

**Comment by ASprinkle** [comment]
There are some spacing issues between words on a few of the bullets. But the design looks great!
