### ISSUE TITLE
As a admin user I want to easily recover from mistyping a permit number while doing a permit number search

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#405]
## Notes
- permit numbers are paygov tracking ids at present

### Acceptance criteria
- [ ] admin user gets helpful error message with focus on permit number field that tells them that the value they have tried to find does not exist.
- [ ] admin user can figure out what they typed wrong and thereby recover

### Tasks
- [ ] change error handling to fire form validation and display message next to input
- [ ] determine wording on message, e.g. Permit number does not exist, along with something helpful about what a permit number should look like.
