### ISSUE TITLE
As a Forest Service employee, I would like the content on the reports page to more accurately reflect the actions to be taken on the page.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#423]
## Notes
 - This was a result from the SME usability testing in sprint 08. It was suggested in usability testing that the reporting have 2 'sections' on the page with an 'or' statement. This change would also require the H1 to change to a more generic title.

For example, the 'sections' could be validate permit by permit id OR create report by date range. When validating a permit by permit ID...a report isn't really being created...its searching by permit id and then displaying the permit information...so it has been considered to be more of a validation tool by the SMEs.

### Acceptance criteria
- [ ] users (admins) are not confused about what they can do on the reports page

### Tasks
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
