### ISSUE TITLE
As a permit purchaser, I need to know that I cannot print the Christmas tree permit I bought online at a forest’s ranger district office.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#424]
## Notes
 - This was a result from the SME usability testing in sprint 08.

### Acceptance criteria
- [ ] User can know that printing will not be available to them at a ranger district office

### Tasks
- [ ] Figure out where optimal location is to warn users about the lack of printer availability at ranger offices
- [ ] Add the warning

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Not an issue that was brought up often. Also, some offices may offer a self-service kiosk.
