### ISSUE TITLE
As a user, I want to be able to purchase a Christmas tree permit using Paypal, and be informed about the option to purchase through Paypal.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#468]
### Acceptance criteria
- [ ] paypal is an available option in pay.gov

### Tasks
- [ ] Update language informing users of all their payment options to include Paypal
- [ ] Update process of communicating with Pay.Gov to have Paypal displayed as an option (Not sure if needed)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
he need for this story came up during the Sprint 9 Review

**Comment by bryanmcfadden** [comment]
@ASprinkle - This also came up a few times by different users in the [sprint 06 ](https://github.com/nciinc/fs-permit-platform/wiki/Sprint-06-Christmas-tree-ePermit-research-results-January-3,-2018 )usability testing - (view details under the "Issues on the site in general" section at the bottom)
Example user quote- _"Most websites offer PayPal as an alternative."_

**Comment by ASprinkle** [comment]
"no" from CFO
