### ISSUE TITLE
Focus rectangle is out of position / misleading USDA link

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#487]
### Acceptance criteria 
- [ ] page is accessible

### Tasks
The focus rectangle is out of position for some reason.  In the image below you'll notice the USDA logo is to the right, but the focus rectangle is a vertical line in the middle of the page.

![image.png](https://images.zenhubusercontent.com/5913513251aa2c30577de73e/ff484263-3016-4574-bf44-b5d1d3fbc033)

Link: 38

### Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested
