### ISSUE TITLE
Navigation Section missing appropriate Role

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#497]
### Acceptance criteria
- [x] element is accessible
### Tasks
Change the <aside> to <nav> or add role="navigation"

HTML5 section elements, such as <nav> and <aside> can help users to quickly skip to certain types of content on a web page. The <aside> element is typically used for things like call-outs or other supplementary content that is not directly related to the main content on the page.

![image.png](https://images.zenhubusercontent.com/5913513251aa2c30577de73e/badfafd2-9582-4b7b-aeda-7d66197e4498)

Linkage:CTF-18

### Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested
