### ISSUE TITLE
Required fields Need visual Notification

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#498]
### Notes
add to all 3 forms - check for optional fields and add * with message if needed

Although the fields have aria-required, they need visual notifications. 

Since all fields are required on this page, you can

"All fields Required" to form.

Linkage:CTF-31

### Acceptance criteria
- [x] forms are accessible

### Tasks
- [x] add text to each admin form and tree application form (will)

### Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
<img width="705" alt="screen shot 2018-03-01 at 12 54 39 pm" src="https://user-images.githubusercontent.com/2058839/36863592-bbbf3f6c-1d4f-11e8-8ae3-950e2b354100.png">

**Comment by sadlerw** [comment]
<img width="1032" alt="screen shot 2018-03-01 at 12 56 21 pm" src="https://user-images.githubusercontent.com/2058839/36863663-fce55c1a-1d4f-11e8-8348-d488e57f521b.png">

**Comment by sadlerw** [comment]
<img width="881" alt="screen shot 2018-03-01 at 12 57 45 pm" src="https://user-images.githubusercontent.com/2058839/36863722-2c44dac6-1d50-11e8-848c-e5607d48a1d8.png">

**Comment by sadlerw** [comment]
<img width="687" alt="screen shot 2018-03-01 at 12 58 17 pm" src="https://user-images.githubusercontent.com/2058839/36863754-4285fd42-1d50-11e8-8800-ffce0f9535b5.png">
