### ISSUE TITLE
As a user, I would like to have the ability to view and print forest maps if they are available so that I can locate Christmas tree cutting areas.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#527]
**Notes**
This is a story that comes from prior usability testing and recent ADMIN review testing.
It will require a little more discussion and was brought up previously in epic #248 which was closed. 

One solution could be the possibility of linking to external maps on forest websites with language like "Cutting area maps are not available for XXXX.... but you can contact the district offices for more information." for forests that do not have maps.

**Acceptance criteria**
- [ ]

**Tasks**
- [ ] tts approval
- [ ] PO approval

**Definition of Done**
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
same as #136
