### ISSUE TITLE
As a user, I would like to see the purchase permit button only in the left hand navigation so that I may not be confused about where a permit is purchased.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#539]
### Notes
This comes from usability testing and the possible confusion of where the purchase permit button is located in the content body of the page.

### Description
Since there are 2 purchase permit buttons and one is located in the content body at the bottom of the dates and times of the forest and its districts, some users believe they are buying a permit for the last district listed rather than the forest itself.

### Tasks
- [ ] remove purchase permit button from content body

### Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by npage123** [comment]
Here's what we're thinking of how the sticky footer could be styled @MelissaBraxton @tram to replace the two existing "Buy Permit" buttons. As it reduces down to a mobile view, just the button would appear knowing the cost text will still be included in the body copy.
![539_1](https://user-images.githubusercontent.com/12956624/37190466-8a2731d2-231f-11e8-8898-c804d67c3b41.jpg)

**Comment by MelissaBraxton** [comment]
I think this is a great direction!  LGTM!

**Comment by ASprinkle** [comment]
Agreed!

**Comment by MelissaBraxton** [comment]
Hey @npage123 (cc @ASprinkle), @bryanmcfadden and @pvd-flexion were talking about this on Friday, and I think we'll need to do a little more work here. This button style is not consistent with our primary button style. Making this button consistent with what's in our style guide will necessitate a change to the background color of the sticky nav. 

In thinking about this, I realized that we have been using a green button as our primary CTA, but this is not consistent with the style established on the intake module. (I had flagged this as an inconsistency in our style guide in issue #199, but it's actually the other way around!)

Check out https://nciinc.github.io/fs-fork-uswds-site/components/buttons/

I've created a card to make the primary CTA button style consistent with the FS-USWDS style guide. https://github.com/nciinc/fs-permit-platform/issues/571

**Comment by sadlerw** [comment]
Melissa - Seth and I went through and analyzed the fs-intake stuff and I think you were right the first time.  The style guide needs to change the primary (usa-button) to the green color (as we are using it now.)  The secondary style needs to be the brown/black which is currently defined as usa-button.  The current secondary (red) needs to just become red buttons.  We will add a task to the style guide story to fix it.  But, I think that the design here is good as is except it isn't consistent with the intake side.  That said, Nate is going to post a sticky footer that is consistent with the existing fs-intake.  We will add an example of that in the footer section on the style guide.

**Comment by sadlerw** [comment]
<img width="1431" alt="screen shot 2018-03-12 at 9 51 12 am" src="https://user-images.githubusercontent.com/2058839/37290691-f46fbb5a-25da-11e8-89c7-7b779af448e1.png">

**Comment by sadlerw** [comment]
<img width="1433" alt="screen shot 2018-03-12 at 9 53 15 am" src="https://user-images.githubusercontent.com/2058839/37290863-5a54b092-25db-11e8-8917-809e4c9a0566.png">

<img width="1156" alt="screen shot 2018-03-12 at 9 54 15 am" src="https://user-images.githubusercontent.com/2058839/37290869-60b97a8a-25db-11e8-9475-d70d9c270e34.png">

**Comment by npage123** [comment]
I think the sticky footer looks good @sadlerw . One minor change, could you please change just the forest name to the Merriweather Bold font?

**Comment by sadlerw** [comment]
forest name is now bold

**Comment by ASprinkle** [comment]
While I understand the "Maximum 5 trees per permit" I believe the language is "...per household" as a restriction for the forests - I can see this causing some questions/confusion by FS admin during review.
Can we remove the "maximum" statement? Isn't it included on the Permit Holder information page before they hit next?

**Comment by bryanmcfadden** [comment]
@ASprinkle - Based on the recent content reviews, I recommend we remove the "Maximum 5 trees per household" text entirely. I would also recommend we hide the forest name and tree cost (show button only) when on mobile to maximize screen real estate for the user.

**Comment by sadlerw** [comment]
ok - that all looks like:

1. on mobile
<img width="449" alt="screen shot 2018-03-14 at 9 53 02 am" src="https://user-images.githubusercontent.com/2058839/37410023-ae19b55e-276d-11e8-89ab-b2fd6c0b8cde.png">

2. medium
<img width="704" alt="screen shot 2018-03-14 at 9 53 17 am" src="https://user-images.githubusercontent.com/2058839/37410063-b7586106-276d-11e8-9480-179ea406ac6d.png">

3. full
<img width="1060" alt="screen shot 2018-03-14 at 9 53 33 am" src="https://user-images.githubusercontent.com/2058839/37410079-be45ff82-276d-11e8-8fbe-ce771af2f601.png">

**Comment by ASprinkle** [comment]
I don't understand the difference between 2 and 3.  I think 2 looks great!

**Comment by sadlerw** [comment]
just a wider screen in 3 than 2

**Comment by MelissaBraxton** [comment]
Looks good with one minor tweak. Per Nate's comment above--the Forest name still doesn't look like Merriweather in the latest screen shot.  Once we fix that, we're good to go!

**Comment by sadlerw** [comment]
I'm not sure why it would be Merriweather - my understanding was that merriweather is for paragraphs, headings, etc. with dense text whereas sans fonts are used for callouts etc. for readability.  @npage123 was there something in the style guide that said to use merriweather here? thanks Will

**Comment by npage123** [comment]
My thought is that it would be an h4 if possible. A heading for the price callout but not stacked?

**Comment by sadlerw** [comment]
the closest thing I can find in the us web design *system* is usa-footer-big-logo-heading  I'll use that

**Comment by sadlerw** [comment]
![screenshot](https://user-images.githubusercontent.com/2058839/37487042-57d65d4a-285e-11e8-83ca-a6d2a09c98c8.jpg)

**Comment by MelissaBraxton** [comment]
LGTM!
