### ISSUE TITLE
WIP: As a COR, I want a maintainable application so that I can meet the FS needs

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-permit-platform#572]
## Notes
**WIP** Catchall card for overall code review comments

## Tasks
*These will be broken out into must, nice to have, etc once compiled.
- [ ] OWASP report
- [ ] Remove comment here: https://github.com/nciinc/fs-permit-platform/blob/sprint-11-development/.cg-deploy/deploy.sh#L4
- [ ] if `build-pa11y-image.sh` is just a wrapper for a direct docker compose command-  let’s remove the this file
- [ ] for `install-dependencies-docker.sh` let’s push each command to a new line

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
@lauraGgit I wasn't quite sure what you were after here so I just did what the tasks said - please let me know if there are additional changes needed.  Thanks, Will
