### ISSUE TITLE
Email: Link purpose for "this link" is not determinable to screen reader users on link focus.

### ISSUE THREAD

**Issue by JohnHewittCriterion** [nciinc/fs-permit-platform#617]
## Notes
The link purpose for "this link" is not meaningful to the screen reader, they only hear "link, this link".
Provide full link text e.g. "Permit available for printing" as the link. 

![image.png](https://images.zenhubusercontent.com/5913513251aa2c30577de73e/edfe7265-497c-4573-b045-b84760f1b0a2)

Linkage: CTF-100
WCAG: 2.4.4 Link Purpose (In Context) 

## Acceptance criteria
- [x] no links with alt of link

## Tasks
- [x] change link text (will)

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested
