### ISSUE TITLE
As an admin requesting forest changes, I need to know what to provide for maps and map details so that the forest information is updated correctly.

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#622]
## Acceptance criteria
- [ ] admin knows what information to include for map updates and new maps when submitting a change request

## Tasks
- [ ] add a minimum map size specification to the form (1200 x 1600)
- [ ] add instructions for including a map description that meets section 508 compliance 
- [ ] add instructions on how to get the current map and map description for updates

**Comment by ASprinkle** [comment]
These specs should be captured for documentation requirements for the GSA point of contact who would be receiving the requests for updates.  The FS Admin may not necessarily understand how to submit their request if they are expected to meet requirements - with the goal of the lightweight google form, one intent is to gather more information about need/frequency of need, and how to improve in the future.
